### PR TITLE
Turn Haskell directory into a Cabal package and build it using Stack

### PR DESCRIPTION
**Pull request by moodmosaic**
This pull request provides an easy way of building the Haskell modules, using [Stack](https://docs.haskellstack.org/en/stable/README/), by doing

```
stack build
```

After that, one may use [hsdev](https://hackage.haskell.org/package/hsdev), [ghc-mod](https://hackage.haskell.org/package/ghc-mod), [Intero](https://hackage.haskell.org/package/intero), or similar, to inspect the code.

---

On my local, it appears to be working as defined:

```
$ stack build

BookingApi-0.1.0.0: configure (lib)
Configuring BookingApi-0.1.0.0...
BookingApi-0.1.0.0: build (lib)
Preprocessing library BookingApi-0.1.0.0...
[1 of 3] Compiling MaîtreD          ( MaîtreD.hs, .stack-work\dist\2672c1f3\build\MaîtreD.o )
[2 of 3] Compiling DB               ( DB.hs, .stack-work\dist\2672c1f3\build\DB.o )
[3 of 3] Compiling Composition      ( Composition.hs, .stack-work\dist\2672c1f3\build\Composition.o )
In-place registering BookingApi-0.1.0.0...
BookingApi-0.1.0.0: copy/register
Installing library in
C:\Users\Nikos\Documents\dependency-rejection-samples\Haskell\.stack-work\install
\4cd6b5f1\lib\x86_64-windows-ghc-7.10.3\BookingApi-0.1.0.0-EQgBsijqqLZ8AXisPWiD7b
Registering BookingApi-0.1.0.0...
```

### CODE REVIEW

**Comment by ploeh** [comment]
Any tips on installing Stack on Windows 10?

**Comment by moodmosaic** [comment]
On Windows, I'm currently aware of these two options:

1. Stack installer ([x86](https://www.stackage.org/stack/windows-i386) or [x64](https://www.stackage.org/stack/windows-x86_64)) from [here](https://docs.haskellstack.org/en/stable/install_and_upgrade/#windows)
2.  Haskell Platform (choose to install Stack - tested with [7.10.3 x64](https://www.haskell.org/platform/download/7.10.3/HaskellPlatform-7.10.3-x86_64-setup.exe)) from [here](https://www.haskell.org/platform/prior.html)

**Comment by ploeh** [comment]
Thank you. I downloaded the Haskell platform; I needed to update it anyway.

**Comment by moodmosaic** [comment]
>I needed to update it anyway.

FWIW, I rarely update my Haskell Platform installation (actually, I can work without Haskell Platform, and do everything from Stack).

---

What I do, every once in a while, is to clean my system from Haskell Platform, and then install a new version of it from scratch. This means I wipe

```
C:\Program Files\Haskell Platform
%AppData%\Roaming\cabal
%AppData%\Roaming\ghc
%AppData%\Roaming\ghc-mod
%AppData%\Roaming\local

```

Then I install a newer version of Haskell Platform — or I just install Stack and then can I have multiple GHC installations, all isolated.

I rarely install something outside Stack. This way I keep any global GHC installations safe from cabal-install<sup>1</sup>.

---

* On existing projects that don't have a `stack.yaml` file, I do `stack init --solver`, so that I can `$ stack build` them, `$ stack ghci` them, and `$ stack test` them (if they have a test suite).
* To start a new project, I pick a template via `$ stack templates` and then I do `$ stack new`
* To build an existing project I do `$ stack build`

If I want to use Atom/ide-haskell/ghc-mod, I make sure to start atom *inside* Stack via `$ stack exec atom.cmd` — but I do also have Sublime Text open with SublimeHaskell/hsdev (because I find hsdev a bit slower than ghc-mod, but it gives better suggestions (it uses hlint) and better type/symbol info).

HTH

<sup>1.  "Well, regarding the name, Cabal is indeed the library that all tools use, e.g. the .cabal file in a project. The bad name here is the build tool "cabal-install" because that has confused the hell out of everyone. There's three things here: a library called Cabal, a build tool called "Stack", and a build tool that should be called "some-haskell-build-tool" like maybe "haskbuilder" but is instead called "cabal-install" because it is some-build-tool-that-uses-the-Cabal-library (although that description works for Stack too). So the two tools with cabal in the name confuse everyone." -- [wolftune](https://github.com/snowdriftcoop/snowdrift/pull/330#issuecomment-220034237)</sup>

**Pull request merged**
